### ISSUE TITLE
support AuthMethod::Integrated

### ISSUE THREAD

**Issue by RickSKy** [zerodaycode/Canyon-SQL#37]
It will be nice to support AuthMethod::Integrated for mssql

**Comment by Pyzyryab** [comment]
@RickSKy hello! Yes, currently, our next target is to rework the process that fills the internal pool of connections handled by Canyon. In this case, the auth method is part of that refactor, but we didn't take it in consideration until now that you mentioned it. So, a way to configure the auth method for mssql will be included in the next release
